spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/asistencia?createDatabaseIfNotExist=false&useSSL=false&serverTimezone=America/Lima
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    include-message: always
